### ISSUE TITLE
Motivation behind robustSmoothSpline weighting scheme

### ISSUE THREAD

**Issue by LTLA** [HenrikBengtsson/aroma.light#14]
**Backstory:** I was looking around for a robust smooth spline fitter, and I was quite pleased to see one implemented so "close to home" (i.e., in a Bioconductor package).

Anyway, I was wondering whether there was a particular statistical motivation behind the use of the reciprocal of the absolute deviation as the weight for each observation? I am more familiar with iterative LOESS where Tukey's biweight is used in each iteration. I believe `MASS::rlm` also iteratively recalculates biweights, which would make it equivalent to a robust spline fitter if combined with `splines::ns`. 

To be clear, I haven't run across any practical issues with `robustSmoothSpline`'s weighting scheme. My only thoughts on this matter are theoretical, where one could imagine getting a huge weight for an observation that happens to lie on the initial fitted line (the contribution of `reps` notwithstanding). In contrast, a biweight would yield a less dramatic decrease in weight as the residual increases, which would avoid the fit being dominated by a few points after one weighting iteration.

**Comment by HenrikBengtsson** [comment]
Hi, it's been a while since I wrote that, but I think the main reason was that by using an L1-estimator for `robustSmoothSpline()` there was no need for a tuning parameter (that is used to account for the variance), which you have for other M-estimators such as Tukey's biweight.  So, fitting under L1 is simply convenient.  Another problem that is avoided is heteroscedasticity - with, say, Tukey's biweight you'd need to adjust the tuning parameter accordingly.

`robustSmoothSpline()` grew out of a need for an alternative to lo(w)ess, which didn't behave well in the extremes (for normalizing various microarray data) and where regular smooth splines where just not robust enough.  You can think of it as an algorithmic "hack"l  I don't think I/we ever showed that the above L1-robustification of smooth spline is statistical correct - I'm not saying it is but it hasn't been shown.

Related: We did a much much more thorough theoretical and empirical studies when developing `calibrateMultiscan()` and `normalizeAffine()` - both use iterative re-weighted L1 estimators.  And their help I did document the rationale for using L1 and not Tukey's biweight, e.g. see Section 'Robustness' of `?calibrateMultiscan`.

So, in the end of the day, I'd say *heteroscedasticity* is the main reason for using an L1 estimator.

Hope this helps

**Comment by LTLA** [comment]
Okay, fair enough. Have you ever encountered practical issues with huge weights from the L1 estimator? I see the default is `reps=1e-15`, and in a genomics application where we have a cloud of thousands of points, I'd imagine that some of them could be pretty close to the initial fitted line. With such a small `reps`, we could get very large weights for points that simply reinforce the initial line:

```r
a <- runif(10000) # just making up stuff
b <- rnorm(10000)
fit <- smooth.spline(a, b, df=5)
w <- 1/(abs(resid(fit))+1e-15)
w[is.na(w)] <- 0 # NA's due to large "tol"

# For plotting; points already on the fitted line get the dominant weights
w <- w/max(w)
o <- order(w)
plot(a[o], b[o], col=rgb(1-w, 1-w, 1-w)[o], pch=16)
curve(predict(fit, x)$y, add=TRUE, col="dodgerblue")

# Next round of fitting; gives an identical line.
fit2 <- smooth.spline(a, b, df=5, w=w)
curve(predict(fit, x)$y, add=TRUE, col="red", lty=2)
```

This seems like it would sharply reduce the ability of later iterations to change the fit, because the only points with noticeable weights are those already on the line. Obviously, the initial fit in the above example is correct, so it wouldn't be a problem that it doesn't change in later iterations. However, you could consider situations where the initial fit is skewed by outliers (but still lying within the point cloud); in this case, you would want later iterations to change the fit, and the huge weights wouldn't help.

Happy to be corrected, though.

**Comment by HenrikBengtsson** [comment]
I think you bring up a good point here.  There is a risk for the weights for some of the data points to completely dominate.    Here is a modified `example("robustSmoothSpline", package = "aroma.light")` that shows how the smooth spline fit is slowly updated through out iterations (until converging after 179 iterations) but also illustrates what looks like the issue your bring up, i.e. all fits seem to go through some of the data points:
```r
library("aroma.light")
data(cars)
attach(cars)
plot(speed, dist, main = "data(cars)  &  robust smoothing splines")
col <- 0
for (iter in seq(1, 200, by = 20)) {
  fit <- robustSmoothSpline(speed, dist, df=10, maxIter = iter)
  lines(fit, col = (col <- col + 1))
}
fit$iter
## 179
```
![robustsmoothspline-iterations](https://user-images.githubusercontent.com/1616850/33246146-0e3ad6c2-d2c6-11e7-94ea-ca94f0307d69.png)

A few reflections:

1. I wonder if in the most extreme case, the iterative process will stick to the initial (L2-estimated) smooth spline, or it can be even damaging.
2. I think, the risk for a very large weight to appear should be higher in regions with large number of data points than in regions with few data points.
3. The risk for this to happen can be adjusted by the `reps` argument.
3. Maybe (not sure) one can argue that argument `reps` is a tuning parameter just as much as the parameter needed by Tukey's biweight function.
4. I don't think it's too hard to generalize `robustSmoothSpline()` to support other re-weighting functions, e.g. such that Tukey's biweight can be used.   `aroma.light::iwpca.matrix()` does this.  Not sure how much time I have myself to look into this anytime soon, but if you want to look into this, I'll be happy to consider a PR.

To answer your question is I/we ever observed issues with `robustSmoothSpline()`:  No, I am not aware of such issues.  It could be because in the worst case we get the initial L2 fit (1) and that we see improvements in the tails which (for our data) is likely to have fewer data points (2).  

Thanks for bringing this up.

**Comment by LTLA** [comment]
Thanks Henrik. I'll put up a PR for the biweight, just in case someone wants to use it.
